const stacksList = [
    'Alibaba Cloud',
    'Amazon RDS',
    'Amazon Web Services (AWS)',
    'Angular',
    'Ansible',
    'Apache Kafka',
    'ASP.NET',
    'Aurelia',
    'AWS Lambda',
    'Backbone.js',
    'Bootstrap',
    'C#',
    'Cassandra',
    'Chef',
    'CircleCI',
    'Contentful',
    'CSS',
    'Dart',
    'Django',
    'Docker',
    'Drupal',
    'Elasticsearch',
    'Elixir',
    'Ember.js',
    'Express.js',
    'Firebase',
    'Flask',
    'Flutter',
    'Git',
    'GitHub Actions',
    'GitLab CI/CD',
    'Golang',
    'Google Cloud Platform (GCP)',
    'GraphQL',
    'Hadoop',
    'Haskell',
    'Heroku',
    'HTML',
    'IBM Cloud',
    'Javascript',
    'Jenkins',
    'Joomla',
    'jQuery',
    'Kafka',
    'Kubernetes',
    'Laravel',
    'Linux',
    'Magento',
    'MariaDB',
    'Machine Learning',
    'Magento',
    'MariaDB',
    'Matplotlib',
    'Memcached',
    'Microsoft Azure',
    'Microservices',
    'Mithril',
    'MongoDB',
    'MySQL',
    'Nginx',
    'NoSQL',
    'Node.js',
    'Objective-C',
    'Oracle Cloud',
    'Oracle Database',
    'Perl',
    'PHP',
    'PostgreSQL',
    'Python Django',
    'React',
    'React Native',
    'Redis',
    'Redux',
    'Ruby',
    'Ruby on Rails',
    'Rust',
    'Sass',
    'Scala',
    'Scikit-Learn',
    'ServiceNow',
    'Svelte',
    'Swift',
    'TensorFlow',
    'Terraform',
    'Unity',
    'Vue.js',
    'Visual Studio',
    'Vue.js',
    'WebAssembly',
    'Xamarin',
    'YAML',
    'Zend Framework',
  ];
  
  export default stacksList;