// export * from './Awards';
// export * from './Certificates'
// export * from './Educations'
// export * from './LoginPage'
// export * from './MyPage'
// export * from './RegisterPage'
// export * from './SearchPortfolios'
export {default as Awards} from './Awards';
export {default as Certificates} from './Certificates'
export {default as Educations} from './Educations'
export {default as Projects} from './Projects'
export {default as ProjectDetail} from './ProjectDetail'
export {default as LoginPage} from './LoginPage'
export {default as MyPage} from './MyPage'
export {default as RegisterPage} from './RegisterPage'
export {default as SearchPortfolios} from './SearchPortfolios'